service: recipe-bible-api

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  # - serverless-localstack

custom:
  serverless-offline:
    httpPort: 21111
    lambdaPort: 3111

provider:
  stage: prod
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  timeout: 30
  region: eu-west-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:eu-west-1:137374389243:table/recipe-bible'

functions:
  get:
    handler: src/api/router.endpoint
    events:
      - http:
          path: /{proxy+}
          method: GET
  post:
    handler: src/api/router.endpoint
    events:
      - http:
          path: /{proxy+}
          method: POST
  put:
    handler: src/api/router.endpoint
    events:
      - http:
          path: /{proxy+}
          method: PUT
  delete:
    handler: src/api/router.endpoint
    events:
      - http:
          path: /{proxy+}
          method: DELETE
